spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project2?serverTimezone=Asia/Seoul
    username: root
    password: rkdalsl060629
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
